"""followers

Revision ID: 474886ef337d
Revises: 839b59904436
Create Date: 2018-10-07 22:12:54.893645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474886ef337d'
down_revision = '839b59904436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
